<?
//MISC
DEFINE( "COST_PER_DAY", .10 );
DEFINE( "DAY_BORROW_LIMIT", 14 );
DEFINE( "DAY_RESERVE_LIMIT", 2 );

//User groups
DEFINE( "GROUP_ADMIN", 1 );
DEFINE( "GROUP_STAFF", 2 );
DEFINE( "GROUP_BORROWER", 3 );

//Genre
DEFINE( "GENRE_ACTION",1);
DEFINE( "GENRE_ADVENTURE",2);
DEFINE( "GENRE_BIOGRAPHY",3);
DEFINE( "GENRE_CHRISTIAN_CLASSICS",4);
DEFINE( "GENRE_COMEDY",5);
DEFINE( "GENRE_COMICS",6);
DEFINE( "GENRE_COURT_ROOM_DRAMA",7);
DEFINE( "GENRE_DETECTIVE",8);
DEFINE( "GENRE_FAMILY_DRAMA",9);
DEFINE( "GENRE_FAN_FICTION",10);
DEFINE( "GENRE_FANTASY",11);
DEFINE( "GENRE_GRAPHIC_NOVELS",12);
DEFINE( "GENRE_HISTORICAL",13);
DEFINE( "GENRE_HORROR",14);
DEFINE( "GENRE_INDIGENOUS_PEOPLE",15);
DEFINE( "GENRE_LOCAL_HISTORY",16);
DEFINE( "GENRE_LITERARY",17);
DEFINE( "GENRE_MEDICAL_FORENSIC",18);
DEFINE( "GENRE_MYSTERY",19);
DEFINE( "GENRE_PICTURE_BOOKS",20);
DEFINE( "GENRE_POETRY",21);
DEFINE( "GENRE_POLICE",22);
DEFINE( "GENRE_ROMANCE",23);
DEFINE( "GENRE_ROMANTIC_COMEDY",24);
DEFINE( "GENRE_SCIENCE",25);
DEFINE( "GENRE_SCIENCE_FICTION",26);
DEFINE( "GENRE_SPORTS",27);
DEFINE( "GENRE_SUSPENSE",28);
DEFINE( "GENRE_THRILLER",29);
DEFINE( "GENRE_WAR",30);


?>